version: 2.1


orbs:
  discord: antonioned/discord@0.1.0

jobs:
  ping:
    docker: 
      - image: cimg/base:stable
    steps:
      - discord/status:
          success_message: Lars says hi
        
      
workflows:
  run-tests:
    jobs:
      - ping
